# -*- coding: utf-8 -*-
"""Sensor_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VduDLR1S2SQFyCYltj0oYggqWWSnWLzV
"""

#import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import zscore
from sklearn.preprocessing import MinMaxScaler

#Load Dataset
df = pd.read_csv("Better_Dataset.csv")

print("First 5 rows:")
print(df.head())

# Basic Info
print("\nShape:", df.shape)
print("\nColumns:", df.columns)
print("\nMissing Values:\n", df.isnull().sum())

# Convert timestamp (if exists)
if 'timestamp' in df.columns:
    df['timestamp'] = pd.to_datetime(df['timestamp'])

# HANDLE MISSING VALUES

# Forward fill
df.fillna(method='ffill', inplace=True)

# Backward fill
df.fillna(method='bfill', inplace=True)

print("\nMissing after cleaning:\n", df.isnull().sum())

# HANDLE OUTLIERS

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("\nShape after outlier removal:", df.shape)

# Z-SCORE METHOD

for col in numeric_cols:
    df[col] = df[col][(np.abs(zscore(df[col])) < 3)]

df.dropna(inplace=True)

# SMOOTHING (REDUCE SENSOR NOISE)

for col in numeric_cols:
    df[col + "_smooth"] = df[col].rolling(window=5).mean()

df.dropna(inplace=True)

# NORMALIZATION

scaler = MinMaxScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# SAVE CLEANED DATA
df.to_csv("cleaned_iot_sensor_data.csv", index=False)

print("\n✅ Data cleaning complete! File saved.")